name: Will it build?

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "38 17 * * 2"

jobs:

  build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build .
